### ISSUE TITLE
Async setState issue

### ISSUE THREAD

**Issue by CircleCurve** [matthew-carroll/flutter_ui_challenge_zoom_menu#5]
When running this part of code, seems like the background code does not work perfectly. I am running on android 

```
E/flutter (22741): The widget on which setState() or markNeedsBuild() was called was:
E/flutter (22741):   MenuScreen-[GlobalKey#07266 MenuScreen](state: _MenuScreenState#fc11a(tickers: tracking 1 ticker))
E/flutter (22741): The widget which was currently being built when the offending call was made was:
E/flutter (22741):   AnimatedMenuListItem(duration: 600ms, dirty, state: _AnimatedMenuListItemState#9fc2e(ticker active))
E/flutter (22741): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3448:11)
E/flutter (22741): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3474:6)
E/flutter (22741): #2      State.setState (package:flutter/src/widgets/framework.dart:1141:14)
E/flutter (22741): #3      _MenuScreenState.setSelectedRenderBox (package:zoom_menu/menu_screen.dart:35:7)
E/flutter (22741): <asynchronous suspension>
E/flutter (22741): #4      _AnimatedMenuListItemState.updateSelectedRenderBox (package:zoom_menu/menu_screen.dart:308:12)
E/flutter (22741): #5      _AnimatedMenuListItemState.build (package:zoom_menu/menu_screen.dart:337:5)
E/flutter (22741): #6      StatefulElement.build (package:flutter/src/widgets/framework.dart:3742:27)
E/flutter (22741): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3654:15)
E/flutter (22741): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
E/flutter (22741): #9      StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
E/flutter (22741): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #11     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
E/flutter (22741): #12     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
E/flutter (22741): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
E/flutter (22741): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4391:32)
E/flutter (22741): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4781:17)
E/flutter (22741): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter (22741): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
E/flutter (22741): #21     ProxyElement.update (package:flutter/src/widgets/framework.dart:3921:5)
E/flutter (22741): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter (22741): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
E/flutter (22741): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3811:5)
E/flutter (22741): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
E/flutter (22741): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3665:16)
E/flutter (22741): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3507:5)
E/flutter (22741): #31     StatelessElement.update (package:flutter/src/widgets/framework.dart:3714:5)
E/flutter (22741): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4673:14)
E/flutter (22741): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2711:15)
E/flutter (22741): #35     ComponentElement.performRebuild (pa

```

Here is my source code 
```dart
setSelectedRenderBox(RenderBox newRenderBox) async {
    final newYTop = newRenderBox.localToGlobal(const Offset(0.0, 0.0)).dy;
    final newYBottom = newYTop + newRenderBox.size.height;
    if (newYTop != selectorYTop) {
      setState(() {
        selectorYTop = newYTop;
        selectorYBottom = newYBottom;
      });
    }
  }

updateSelectedRenderBox() {
    final renderBox = context.findRenderObject() as RenderBox;
    if (renderBox != null && widget.isSelected) {
      (menuScreenKey.currentState as _MenuScreenState).setSelectedRenderBox(renderBox);
    }
  }
```
I think this issue appear because of update one frame at a multiple 
I don't know whether is a better solution or not. I have tried to add a delay time for it. 
```dart
double selectorYTop;
  double selectorYBottom;
  bool isRefresh = false;

  setSelectedRenderBox(RenderBox newRenderBox) async {
    final newYTop = newRenderBox.localToGlobal(const Offset(0.0, 0.0)).dy;
    final newYBottom = newYTop + newRenderBox.size.height;
    if (newYTop != selectorYTop) {
      if (isRefresh == false) {
        isRefresh = true;
        await new Future.delayed(const Duration(milliseconds: 10));
        setState(() {
          selectorYTop = newYTop;
          selectorYBottom = newYBottom;
          isRefresh = false;
        });
      }
    }
  }
```

Please take a look of it. Thanks @matthew-carroll

**Comment by ejabu** [comment]
As demonstrated in his [video (here)](https://youtu.be/6CEjnCVdgRM?t=8417), it showed he encountered the same issue. But somehow it managed to be succeed after he put **async** in `setSelectedRenderBox`.

Me to always got the same error in first click of ButtonDrawer. Therefore, I cannot automatically test it using flutter-driver.

**Comment by ejabu** [comment]
Finally, I managed to make it succeed without markNeedsBuild exceptions.

As soon AnimatedMenuListItem rendered / build, we scheduled Selected Box indicator to be positioned.

Please consider this code

``` dart
  void afterBuild(Duration duration) {
    updateSelectedRenderBox();
  }

  @override
  Widget build(BuildContext context) {
    // updateSelectedRenderBox();
    WidgetsBinding.instance.addPostFrameCallback(afterBuild);
   
    .....
  }

```
